import Link from "next/link";
import { Inter } from "next/font/google";
import { BsChevronDown } from "react-icons/bs";
import { MdOutlineSettings, MdOutlineTerminal, MdOutlineBuild, MdOutlineFolder, MdSettingsBackupRestore } from "react-icons/md";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const globalFont = Inter({ subsets: ['latin'] }); 

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={globalFont.className}>
                <nav className="flex items-center bg-dark border-b border-light h-14 px-4 gap-4">
                    <Link href="/">
                        <img src="/minehut.svg" alt="Minehut Logo" className="w-40 h-full mr-4" />
                    </Link>
                    <span className="flex-grow" />
                </nav>
                {children}
            </body>
        </html>
    );
}
